### ISSUE TITLE
Issue while uploading in ios

### ISSUE THREAD

**Issue by sanalkv** [abhimortal6/simple_s3#3] opened 2021-05-07 12:14 UTC
`simple_s3/SwiftSimpleS3Plugin.swift:110: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Lost connection to device.
`

**Comment by abhimortal6** [comment] 2021-05-07 12:58
> `simple_s3/SwiftSimpleS3Plugin.swift:110: Fatal error: Unexpectedly found nil while unwrapping an Optional value Lost connection to device. `

Insufficient information please provide reproduction details, device details.

**Comment by sanalkv** [comment] 2021-05-10 04:51
` _simpleS3.uploadFile(
        File(imagePath),
        _bucketName,
        _idpool,
        AWSRegions.usEast1,
        accessControl: S3AccessControl.publicReadWrite,
        debugLog: true,
      );`

Currently I'm calling the method like this and i have the following error.

`
flutter: Content Type: image/jpeg
flutter:
flutter: Status: Error
flutter:
flutter: S3 Upload Error------------------>
`

**Comment by sanalkv** [comment] 2021-05-10 05:15
okay, currently its only working for android. For IOS i'm having the following error.
`HostId=xxxx, ResponseObjectError={
    Code = AccessDenied;
    HostId = "xxxx";
    Message = "Access Denied";
    RequestId = xxxx;
}`
Is it because i have given some wrong permission ?

**Comment by abhimortal6** [comment] 2021-05-10 05:21
Okay this seems to be a policy issue. Please refer to this [link](https://github.com/aws-amplify/aws-sdk-ios/issues/103)

**Comment by sanalkv** [comment] 2021-05-10 05:42
This is what I'm using currently.
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::app_name"
        },
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::app_name/*"
        }
    ]
}`

Do you think there is anything wrong with this policy ?

**Comment by abhimortal6** [comment] 2021-05-10 06:19
Try removing /*. As suggested in link above.

**Comment by sanalkv** [comment] 2021-05-10 06:23
I removed and tried, but that is actually required. Now i have updated the policy but i have come across some other error.

The policy the i used 

```
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::ageye-app",
                "arn:aws:s3:::ageye-app/*"
            ]
        }
    ]
}
```

The error that I'm getting now

`AWSTMDiskCache.m (491) ERROR: The data couldn’t be written because it isn’t in the correct format.`

**Comment by abhimortal6** [comment] 2021-05-10 06:26
Yes I think this confirms it, it's just policy issue. Keep one instance "arn:aws:s3:::ageye-app" only.

`{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::ageye-app"
            ]
        }
    ]
}`

**Comment by abhimortal6** [comment] 2021-05-10 06:33
That's my bottleneck brother. I think you should consult someone with AWS S3 knowledge. Sorry!

**Comment by sanalkv** [comment] 2021-05-10 06:41
Do you have any idea about this error ? 'AWSTMDiskCache.m (491) ERROR: The data couldn’t be written because it isn’t in the correct format.

**Comment by abhimortal6** [comment] 2021-05-10 06:45
Nope

**Comment by sanalkv** [comment] 2021-05-10 06:51
The problem have been solved. Thanks for the help. May be in future updates you can try to pass the native error using result.error("error", "aws error.", null) instead of returning false. so that you can throw that error in flutter side. Currently it was hard for me to debug because the error was printed in xcode but not in vscode.

**Comment by abhimortal6** [comment] 2021-05-10 06:55
Great and yes thanks. By the way these logs are from AWS SDK, logs are not **captured** to be sent in result as error. For reference [here](https://github.com/flutter/flutter/issues/42410). Closing the issue

**Comment by abhimortal6** [comment] 2021-05-10 06:56
Great and yes thanks. By the way these logs are from AWS SDK, logs are not **captured** to be sent in result as error. For reference [here](https://github.com/flutter/flutter/issues/42410). Closing the issue

**Closed by abhimortal6** 2021-05-10 06:56 UTC

**Comment by poojabokdia** [comment] 2021-10-06 12:13
@sanalkv  Hey how did you solve this AWSTMDiskCache.m (491) ERROR: The data couldn’t be written because it isn’t in the correct format?

**Comment by federico-amura-kenility** [comment] 2022-03-22 21:40
@poojabokdia  you found any solution to  AWSTMDiskCache.m (491) ERROR: The data couldn’t be written because it isn’t in the correct format??
